dist: xenial

language: java

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk-ea

matrix:
  fast_finish: true
  allow_failures:
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: openjdk11
    - jdk: openjdk12
    - jdk: openjdk-ea
